# Generated by Django 4.2.5 on 2023-09-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_shelve_rename_stock_price_stockitem_cost_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shelve",
            old_name="name",
            new_name="title",
        ),
    ]
