# Generated by Django 4.2.5 on 2023-09-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_rename_name_shelve_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
