# Generated by Django 4.2.5 on 2023-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0004_stockitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=7, null=True
            ),
        ),
    ]
